create table IF NOT EXISTS ANIMAL_INS
(
    ANIMAL_ID        VARCHAR(255) NOT NULL,
    ANIMAL_TYPE      VARCHAR(255) NOT NULL,
    DATETIME         DATETIME     NOT NULL,
    INTAKE_CONDITION VARCHAR(255) NOT NULL,
    NAME             VARCHAR(255) NULL,
    SEX_UPON_INTAKE  VARCHAR(255) NOT NULL
);

# 동물 보호소에 들어온 모든 동물의 이름과 보호 시작일을 조회하는 SQL문을 작성해주세요.
# 이때 결과는 ANIMAL_ID 역순으로 보여주세요.
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC